# -*- coding: utf-8 -*-
"""IBMbasicpro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/IBM-EPBL/IBM-Project-2613-1658478173/blob/main/IBMbasicpro.ipynb
"""

string="Hi there Sam!"
print(string.split())

"""#1.Split this string

#2.Use.format()to print the following string
"""

planet="Earth"
diameter=12742
print('The diameter of {} is {} kilometers.'.format(planet,diameter));

"""

#3.In this nest dictionary grab the word "hello"

"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

"""

#4.1.Create an array of 10 zeros?

"""

import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

"""#4.2.Create an array of 10 fives?"""

import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

"""

#5.Create an array of all the even integers from 20 to 35

"""

import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 36")
print(array)

"""

#6.Create a 3x3 matrix with values ranging from 0 to 8

"""

import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

"""

#7.Concatinate a and b

"""

import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6])
print(b)
print('\n---Result of a and b---')
print(np.concatenate((a, b)))

"""

#8.Create a dataframe with 3 rows and 2 columns

"""

import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)

"""

#9.Generate the series of dates from 1st Jan,2023 to 10th Feb,2023

"""

import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
 
# initializing periods
periods = datetime.datetime.strptime("10-02-2023", "%d-%m-%Y")
 
date_generated = pd.date_range(test_date, periods)
print(date_generated.strftime("%d-%m-%Y"))

"""

#10.Create 2D list of DataFrame

"""

import pandas as pd  
      
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 
      
df = pd.DataFrame(lists, columns =['ID', 'Name', 'Age']) 
print(df)